= Contrato de Arrendamiento
Santiago Neira
2024-10-23

// Generales
:fechaContrato: 25 de Octubre del 2024

// Datos Propiedad


// Datos Arrendador
:arrendador: Juan Pérez
:nacionalidadArrendador: chilena
:estadoCivilArrendador: soltero
:profesionArrendador: Ingeniero en Informática
:rutArrendador: 12.345.678-5
:domicilioArrendador: Calle Siempreviva 1234, Santiago
:telefonoArrendador: 9 9999 9999

// Datos Arrendatario
:arrendatario: Romina Rojas


// Datos Codeudor

En Santiago de Chile, a {fechaContrato}, comparecen, por una parte, como arrendador, {arrendador}, {nacionalidadArrendador}, {estadoCivilArrendador}, {profesionArrendador}, cédula nacional de identidad número {rutArrendador}, domiciliado en {domicilioArrendador}, teléfono {telefonoArrendador} y por la otra parte, como arrendatario, {arrendatario}, {nacionalidadArrendatario}, {estadoCivilArrendatario}, {profesionArrendatario}, cédula nacional de identidad número {rutArrendatario}, teléfono {telefonoArrendatario}, los comparecientes mayores de edad quienes exponen que han convenido en el contrato de arriendo que consta de las declaraciones y estipulaciones siguientes:

== 1. Partes del contrato

*Prestador de servicios*: Juan Pérez, identificado con cédula XXXX, con domicilio en Calle Falsa 123.

*Cliente*: Empresa ABC S.A., representada por María López, con domicilio en Avenida Principal 456.

== 2. Objeto del contrato

El prestador de servicios acuerda prestar los siguientes servicios al cliente:

- Asesoría legal en derecho comercial.
- Redacción de documentos legales.

== 3. Duración del contrato

Este contrato tendrá una duración de 12 meses a partir de la fecha de firma.

== 4. Monto y forma de pago

El cliente pagará al prestador de servicios la suma de $XXXX por cada mes de trabajo.

== 5. Cláusulas adicionales

- El presente contrato se firma por ambas partes.
- ...

== Firma


image::lineafirma.svg[width=200,align=center]
[.text-center]
Juan Pérez +
12.345.678-5


image::lineafirma.svg[width=200,align=left]
María Rojas
12.345.678-5



[cols="1,>1", frame=none, grid=none]
|=== 

a| image::lineafirma.svg[width=200,align=left]
a| image::lineafirma.svg[width=200,align=right]

| Juan Pérez
| María López
|===
